project:
  type: website
  output-dir: ../docs

website:
  title: "DSAN 6000 Big Data Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: eda.qmd
        text: Exploratory Data Analysis
      - href: nlp.qmd
        text: Natural Language Processing
      - href: ml.qmd
        text: Machine Learning
      - href: conclusion.qmd
        text: Conclusion
      - href: report.qmd
        text: Report
  page-footer:
    left: |
      DSAN 6000 Big Data Analytics Project
    right: |
      Made with [Quarto](https://quarto.org/)

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    code-fold: false
    code-tools: false
